on:
  push:
    branches:
      - main

name: build

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install packages
        run: |
          R -e 'install.packages(c("knitr","fs","stringr","dplyr","stringi","magrittr"))'
          R -e 'renv::restore()'
      - name: Make Page
        run : Rscript pageMaker.R




      